### ISSUE TITLE
开放接口里面有很多都没有，你的接口是自己扒的吗？

### ISSUE THREAD

**Issue by xiaohuoni** [okoala/yuque#2]
我年前也搞了一个rn版本的app，发现有些数据没有！

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/52550445-20bca100-2e13-11e9-9431-75a5ea9debdd.png)

**Comment by okoala** [comment]
不是啊，官方的接口。现在就对接了一个，其他的还没开始写啊。等玩完回来继续搞

**Comment by xiaohuoni** [comment]
那你消息这些接口，应该都没有吧！！我找了语雀的产品经理，他说年后开这些接口！

**Comment by okoala** [comment]
@xiaohuoni
一期只会依赖开放接口来搞，以及添加一些实用的功能～
